"""Assemble the Cloudflare Worker bundle.

Cloudflare's Python runtime has no filesystem to read the dataset from, and
`aircrew/` is imported unchanged -- the whole point is that the deployed engine
is the same code as the local one, not a port of it. So this script does three
things and nothing else:

  1. copies aircrew/ into dist/ (minus server.py, which the Worker replaces),
  2. writes dist/dataset_bundle.py, the nine JSON tables as one Python module,
  3. copies web/index.html into dist/public/.

Run it before every deploy:  python worker/build.py

`dist/` is generated and gitignored. Deploying a stale bundle is the failure
this guards against, so it is rebuilt from scratch each time.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WORKER = ROOT / "worker"
DIST = WORKER / "dist"
DATA = ROOT / "problem_statement" / "data"

# The Worker serves the API and the page; it does not run the CLI, the
# scoreboard or the replay harness, and every module it does not need is
# module-parse time it does not spend on a cold start.
SKIP = {"server.py", "cli.py", "scoreboard.py", "replay.py"}

REQUIRED = [
    "flights", "crew", "rosters", "duty_clocks", "reserve_pool",
    "certifications", "rules", "costs", "risk_signals", "scenarios",
    "questions",
]


def main() -> None:
    if DIST.exists():
        shutil.rmtree(DIST)
    (DIST / "public").mkdir(parents=True)

    # 1. the engine, unchanged
    package = DIST / "aircrew"
    package.mkdir()
    for src in sorted((ROOT / "aircrew").glob("*.py")):
        if src.name in SKIP:
            continue
        shutil.copy2(src, package / src.name)

    # 2. the dataset, as a module. Stored as JSON text and parsed on first use
    #    rather than written out as Python literals: a 384 KB duty_clocks.json
    #    becomes an expression the runtime has to compile, and compiling it is
    #    slower than parsing it.
    tables = {name: (DATA / f"{name}.json").read_text(encoding="utf-8")
              for name in REQUIRED}
    lines = [
        '"""The published dataset, bundled. Generated by worker/build.py."""',
        "",
        "import json",
        "",
        "_RAW = {",
    ]
    for name, text in tables.items():
        lines.append(f"    {name!r}: {json.dumps(text)},")
    lines += [
        "}",
        "",
        "",
        "def tables():",
        '    """Parsed once; the Worker holds it for the life of the isolate."""',
        "    return {name: json.loads(raw) for name, raw in _RAW.items()}",
        "",
    ]
    (DIST / "dataset_bundle.py").write_text("\n".join(lines), encoding="utf-8")

    # 3. the page
    shutil.copy2(WORKER / "entry.py", DIST / "entry.py")
    shutil.copy2(ROOT / "web" / "index.html", DIST / "public" / "index.html")

    total = sum(f.stat().st_size for f in DIST.rglob("*") if f.is_file())
    print(f"built {DIST.relative_to(ROOT)}  ({total / 1024:.0f} KB)")
    for f in sorted(DIST.rglob("*.py")):
        print(f"  {f.relative_to(DIST)}  {f.stat().st_size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
